import type {
  Event,
  Workshop,
  Project,
  Resource,
  GalleryItem,
  Achievement,
  TeamMember,
  Announcement,
} from "@/types";

export const EVENTS: Event[] = [
  {
    id: "1",
    slug: "aerospace-engineering-summit-2026",
    title: "Aerospace Engineering Summit 2026",
    description:
      "Join us for an immersive summit featuring industry leaders from Boeing, Airbus, and ISRO. Explore the latest in aerospace engineering, propulsion systems, and composite materials. This flagship event brings together students, faculty, and industry professionals for a day of technical sessions, panel discussions, and networking.",
    shortDescription: "Flagship aerospace summit with industry leaders from Boeing, Airbus, and ISRO.",
    category: "technical-talk",
    status: "upcoming",
    banner: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&h=600&fit=crop",
    date: "2026-04-15",
    time: "09:00",
    endTime: "17:00",
    venue: "Technology Tower, VIT Chennai",
    location: {
      lat: 12.8406,
      lng: 80.1534,
      address: "Technology Tower, VIT Chennai, Kelambakkam Road, Chennai 600127",
    },
    agenda: [
      { time: "09:00", title: "Registration & Welcome", description: "Check-in and networking breakfast" },
      { time: "10:00", title: "Keynote: Future of Aerospace", description: "Dr. Rajesh Kumar, Boeing India" },
      { time: "11:30", title: "Panel: Sustainable Aviation", description: "Industry experts discussion" },
      { time: "13:00", title: "Lunch Break", description: "Networking lunch" },
      { time: "14:00", title: "Technical Sessions", description: "Parallel tracks on propulsion & materials" },
      { time: "16:00", title: "Closing Ceremony", description: "Awards and certificate distribution" },
    ],
    speakers: [
      {
        id: "s1",
        name: "Dr. Rajesh Kumar",
        title: "Senior Aerospace Engineer",
        company: "Boeing India",
        photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
        bio: "20+ years in aerospace design and propulsion systems.",
      },
      {
        id: "s2",
        name: "Prof. Anita Sharma",
        title: "Head of Research",
        company: "ISRO",
        photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
        bio: "Leading researcher in satellite propulsion and thermal management.",
      },
    ],
    sponsors: [
      { id: "sp1", name: "Boeing", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Boeing_full_logo.svg", tier: "platinum" },
      { id: "sp2", name: "Siemens", logo: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Siemens-logo.svg", tier: "gold" },
    ],
    gallery: [],
    brochureUrl: "/downloads/aerospace-summit-brochure.pdf",
    certificateAvailable: true,
    downloads: [
      { name: "Event Brochure", url: "/downloads/aerospace-summit-brochure.pdf" },
      { name: "Agenda PDF", url: "/downloads/aerospace-summit-agenda.pdf" },
    ],
    maxRegistrations: 300,
    registeredCount: 187,
    featured: true,
  },
  {
    id: "2",
    slug: "solidworks-masterclass",
    title: "SolidWorks Masterclass",
    description:
      "A comprehensive hands-on workshop covering advanced SolidWorks modeling, assembly design, simulation, and rendering. Perfect for beginners and intermediate users looking to enhance their CAD skills.",
    shortDescription: "Advanced SolidWorks modeling, assembly, and simulation workshop.",
    category: "workshop",
    status: "upcoming",
    banner: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&h=600&fit=crop",
    date: "2026-03-20",
    time: "10:00",
    endTime: "16:00",
    venue: "CAD Lab, Block B, VIT Chennai",
    location: {
      lat: 12.841,
      lng: 80.154,
      address: "CAD Lab, Block B, VIT Chennai",
    },
    agenda: [
      { time: "10:00", title: "Introduction to Advanced Modeling" },
      { time: "11:30", title: "Assembly Design & Mates" },
      { time: "13:00", title: "Lunch Break" },
      { time: "14:00", title: "Simulation & Analysis" },
      { time: "15:30", title: "Rendering & Documentation" },
    ],
    speakers: [],
    sponsors: [],
    gallery: [],
    certificateAvailable: true,
    downloads: [],
    maxRegistrations: 50,
    registeredCount: 42,
    featured: true,
  },
  {
    id: "3",
    slug: "tata-motors-industrial-visit",
    title: "Tata Motors Industrial Visit",
    description:
      "An exclusive industrial visit to Tata Motors manufacturing facility. Witness automotive production lines, quality control processes, and R&D facilities firsthand.",
    shortDescription: "Visit Tata Motors manufacturing facility and R&D center.",
    category: "industrial-visit",
    status: "past",
    banner: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=1200&h=600&fit=crop",
    date: "2025-11-10",
    time: "08:00",
    endTime: "18:00",
    venue: "Tata Motors, Pune",
    location: {
      lat: 18.5204,
      lng: 73.8567,
      address: "Tata Motors Limited, Pune, Maharashtra",
    },
    agenda: [
      { time: "08:00", title: "Departure from VIT Chennai" },
      { time: "14:00", title: "Factory Tour" },
      { time: "16:00", title: "Q&A with Engineers" },
      { time: "18:00", title: "Return Journey" },
    ],
    speakers: [],
    sponsors: [],
    gallery: [
      "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=600&fit=crop",
    ],
    certificateAvailable: true,
    downloads: [],
    registeredCount: 45,
    featured: false,
  },
  {
    id: "4",
    slug: "human-powered-vehicle-challenge",
    title: "Human Powered Vehicle Challenge",
    description:
      "Design and build a human-powered vehicle for the ASME HPVC competition. Teams compete in speed, endurance, and design innovation categories.",
    shortDescription: "Design and build human-powered vehicles for ASME HPVC competition.",
    category: "competition",
    status: "upcoming",
    banner: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop",
    date: "2026-05-01",
    time: "09:00",
    venue: "Sports Complex, VIT Chennai",
    location: {
      lat: 12.8406,
      lng: 80.1534,
      address: "Sports Complex, VIT Chennai",
    },
    agenda: [],
    speakers: [],
    sponsors: [],
    gallery: [],
    certificateAvailable: true,
    downloads: [],
    maxRegistrations: 100,
    registeredCount: 56,
    featured: true,
  },
];

export const WORKSHOPS: Workshop[] = [
  {
    id: "w1",
    slug: "ansys-fea-workshop",
    title: "ANSYS FEA Workshop",
    overview:
      "Learn finite element analysis using ANSYS Workbench. Cover static structural analysis, modal analysis, thermal analysis, and result interpretation with real engineering case studies.",
    prerequisites: ["Basic mechanics of materials", "Engineering mathematics", "Laptop with ANSYS installed"],
    instructor: {
      name: "Dr. Venkatesh R",
      title: "Associate Professor, Mechanical Engineering",
      photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop",
      bio: "15+ years of FEA research and consulting experience.",
    },
    learningOutcomes: [
      "Set up and run static structural analyses",
      "Perform modal and thermal simulations",
      "Interpret stress and deformation results",
      "Apply mesh refinement techniques",
      "Generate professional analysis reports",
    ],
    resources: [
      { name: "ANSYS Student Edition", url: "https://www.ansys.com/academic", type: "software" },
      { name: "Workshop Manual", url: "/downloads/ansys-workshop-manual.pdf", type: "pdf" },
    ],
    certificateAvailable: true,
    gallery: [
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop",
    ],
    date: "2026-03-25",
    duration: "2 Days",
    venue: "Simulation Lab, VIT Chennai",
    banner: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop",
    maxSeats: 40,
    registeredCount: 35,
  },
  {
    id: "w2",
    slug: "matlab-for-mechanical-engineers",
    title: "MATLAB for Mechanical Engineers",
    overview:
      "Master MATLAB for mechanical engineering applications including numerical methods, control systems, signal processing, and data visualization.",
    prerequisites: ["Basic programming knowledge", "Engineering mathematics"],
    instructor: {
      name: "Prof. Meera Krishnan",
      title: "Assistant Professor",
      photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop",
      bio: "Expert in computational methods and MATLAB applications.",
    },
    learningOutcomes: [
      "Write efficient MATLAB scripts and functions",
      "Solve differential equations numerically",
      "Create publication-quality plots",
      "Implement control system simulations",
      "Process and analyze experimental data",
    ],
    resources: [
      { name: "MATLAB Online", url: "https://matlab.mathworks.com", type: "software" },
    ],
    certificateAvailable: true,
    gallery: [],
    date: "2026-04-05",
    duration: "1 Day",
    venue: "Computer Lab, Block A",
    banner: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop",
    maxSeats: 60,
    registeredCount: 48,
  },
];

export const PROJECTS: Project[] = [
  {
    id: "p1",
    slug: "autonomous-delivery-drone",
    title: "Autonomous Delivery Drone",
    description:
      "A fully autonomous quadrotor drone designed for campus delivery with obstacle avoidance, GPS navigation, and payload capacity of 2kg. Features custom 3D-printed frame and flight controller integration.",
    objectives: [
      "Design lightweight aerodynamic frame",
      "Implement autonomous navigation algorithms",
      "Integrate obstacle detection sensors",
      "Achieve 15-minute flight endurance",
    ],
    category: "aerospace",
    images: [
      "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1508614589041-e8951056679f?w=800&h=600&fit=crop",
    ],
    technologies: ["Carbon Fiber", "Brushless Motors", "LiPo Battery", "GPS Module"],
    software: ["SolidWorks", "ANSYS Fluent", "MATLAB", "Arduino"],
    teamMembers: [
      { name: "Arjun S", role: "Team Lead" },
      { name: "Priya M", role: "Aerodynamics" },
      { name: "Karthik R", role: "Controls" },
    ],
    githubUrl: "https://github.com/asme-vit/delivery-drone",
    awards: ["Best Innovation Award 2025"],
    year: 2025,
    featured: true,
  },
  {
    id: "p2",
    slug: "formula-student-race-car",
    title: "Formula Student Race Car",
    description:
      "Student-built formula race car for Formula Bharat competition. Features carbon fiber monocoque, turbocharged engine, and advanced suspension geometry.",
    objectives: [
      "Design FSAE-compliant race car",
      "Optimize power-to-weight ratio",
      "Implement data acquisition system",
      "Compete at Formula Bharat 2025",
    ],
    category: "automobile",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    ],
    technologies: ["Carbon Fiber", "Turbo Engine", "Sequential Gearbox"],
    software: ["CATIA", "ANSYS", "OptimumLap"],
    teamMembers: [
      { name: "Rahul V", role: "Team Captain" },
      { name: "Sneha K", role: "Chassis Lead" },
    ],
    awards: ["Formula Bharat - 5th Overall 2024"],
    year: 2024,
    featured: true,
  },
  {
    id: "p3",
    slug: "6-axis-robotic-arm",
    title: "6-Axis Robotic Arm",
    description:
      "Precision 6-DOF robotic arm for pick-and-place operations with computer vision integration and collaborative safety features.",
    objectives: [
      "Achieve ±0.1mm positioning accuracy",
      "Implement inverse kinematics",
      "Integrate vision-based object detection",
    ],
    category: "robotics",
    images: [
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=600&fit=crop",
    ],
    technologies: ["Servo Motors", "Arduino Mega", "OpenCV"],
    software: ["Fusion 360", "ROS", "Python"],
    teamMembers: [{ name: "Vikram T", role: "Lead Developer" }],
    githubUrl: "https://github.com/asme-vit/robotic-arm",
    year: 2025,
    featured: false,
  },
];

export const RESOURCES: Resource[] = [
  {
    id: "r1",
    title: "Mechanics of Materials - Complete Notes",
    description: "Comprehensive notes covering stress, strain, bending, torsion, and failure theories.",
    category: "mechanical-notes",
    fileUrl: "/downloads/mom-notes.pdf",
    fileType: "pdf",
    downloads: 1250,
    tags: ["MOM", "Strength of Materials", "Semester 3"],
    uploadedAt: "2025-08-15",
  },
  {
    id: "r2",
    title: "SolidWorks Beginner Tutorial Series",
    description: "Step-by-step SolidWorks tutorials from basic sketches to advanced assemblies.",
    category: "solidworks",
    fileUrl: "/downloads/solidworks-tutorials.pdf",
    fileType: "pdf",
    downloads: 890,
    tags: ["CAD", "SolidWorks", "Modeling"],
    uploadedAt: "2025-09-01",
  },
  {
    id: "r3",
    title: "ANSYS Static Structural Analysis Guide",
    description: "Complete guide to setting up and running static structural analyses in ANSYS.",
    category: "ansys",
    fileUrl: "/downloads/ansys-guide.pdf",
    fileType: "pdf",
    downloads: 567,
    tags: ["FEA", "ANSYS", "Simulation"],
    uploadedAt: "2025-10-20",
  },
  {
    id: "r4",
    title: "Mechanical Engineering Resume Template",
    description: "Professional resume template optimized for mechanical engineering placements.",
    category: "resume-templates",
    fileUrl: "/downloads/me-resume-template.docx",
    fileType: "doc",
    downloads: 2100,
    tags: ["Resume", "Placement", "Career"],
    uploadedAt: "2025-07-10",
  },
  {
    id: "r5",
    title: "Top 100 Interview Questions for ME",
    description: "Curated list of technical and HR interview questions for mechanical engineering roles.",
    category: "interview-questions",
    fileUrl: "/downloads/me-interview-questions.pdf",
    fileType: "pdf",
    downloads: 1800,
    tags: ["Interview", "Placement", "HR"],
    uploadedAt: "2025-11-05",
  },
];

export const GALLERY: GalleryItem[] = [
  {
    id: "g1",
    title: "Aerospace Summit 2025",
    category: "events",
    imageUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&h=600&fit=crop",
    thumbnailUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=300&fit=crop",
    date: "2025-10-15",
  },
  {
    id: "g2",
    title: "SolidWorks Workshop",
    category: "workshops",
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop",
    thumbnailUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop",
    date: "2025-09-20",
  },
  {
    id: "g3",
    title: "Tata Motors Visit",
    category: "industrial-visits",
    imageUrl: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800&h=600&fit=crop",
    thumbnailUrl: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=400&h=300&fit=crop",
    date: "2025-11-10",
  },
  {
    id: "g4",
    title: "HPVC Team Victory",
    category: "competitions",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    thumbnailUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    date: "2025-06-15",
  },
  {
    id: "g5",
    title: "Team Building Retreat",
    category: "team-building",
    imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=600&fit=crop",
    thumbnailUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&h=300&fit=crop",
    date: "2025-08-01",
  },
  {
    id: "g6",
    title: "National Award Ceremony",
    category: "achievements",
    imageUrl: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&h=600&fit=crop",
    thumbnailUrl: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=400&h=300&fit=crop",
    date: "2025-12-01",
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "a1",
    title: "ASME HPVC - 2nd Place National",
    type: "competition",
    description: "Secured 2nd place in the Human Powered Vehicle Challenge at the national level.",
    year: 2025,
    members: ["Arjun S", "Priya M", "Karthik R", "Divya N"],
    organization: "ASME India",
  },
  {
    id: "a2",
    title: "Research Paper - Composite Materials",
    type: "publication",
    description: "Published research on carbon fiber composite optimization in ASME Journal.",
    year: 2025,
    members: ["Dr. Venkatesh R", "Sneha K"],
    organization: "ASME Journal of Engineering Materials",
  },
  {
    id: "a3",
    title: "Boeing Internship Program",
    type: "internship",
    description: "5 members selected for Boeing India summer internship program.",
    year: 2025,
    members: ["Rahul V", "Ananya P", "Mohit S", "Kavya R", "Aditya M"],
    organization: "Boeing India",
  },
  {
    id: "a4",
    title: "Best Student Chapter Award",
    type: "national-award",
    description: "Recognized as the Best ASME Student Chapter in South India region.",
    year: 2024,
    members: ["ASME VIT Team"],
    organization: "ASME India Section",
  },
  {
    id: "a5",
    title: "Formula Bharat - 5th Overall",
    type: "competition",
    description: "Achieved 5th overall position at Formula Bharat 2024 competition.",
    year: 2024,
    members: ["Formula Student Team"],
    organization: "Formula Bharat",
  },
  {
    id: "a6",
    title: "Google Placement - 12 Members",
    type: "placement",
    description: "12 ASME members placed at Google, Microsoft, and Amazon in 2024-25.",
    year: 2025,
    members: ["Various Members"],
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "t1",
    name: "Dr. S. Rajasekaran",
    role: "Faculty Coordinator",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/rajasekaran",
    email: "rajasekaran@vit.ac.in",
    bio: "Professor with 20+ years in thermal engineering and ASME chapter mentorship.",
    team: "faculty-coordinator",
    order: 1,
  },
  {
    id: "t2",
    name: "Dr. Priya Venkatesh",
    role: "Faculty Advisor",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1573497019940-1c28c88b4aae?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/priyav",
    email: "priya.v@vit.ac.in",
    bio: "Expert in manufacturing processes and student research guidance.",
    team: "faculty-advisor",
    order: 2,
  },
  {
    id: "t3",
    name: "Arjun Sharma",
    role: "Chairperson",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/arjunsharma",
    email: "arjun.sharma@vitstudent.ac.in",
    bio: "Final year ME student passionate about aerospace engineering and leadership.",
    team: "chairperson",
    order: 3,
  },
  {
    id: "t4",
    name: "Priya Menon",
    role: "Vice Chairperson",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/priyamenon",
    email: "priya.menon@vitstudent.ac.in",
    bio: "Specializing in robotics and automation with industry internship experience.",
    team: "vice-chairperson",
    order: 4,
  },
  {
    id: "t5",
    name: "Karthik Reddy",
    role: "Secretary",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/karthikreddy",
    email: "karthik.reddy@vitstudent.ac.in",
    bio: "Organizing events and managing chapter communications with precision.",
    team: "secretary",
    order: 5,
  },
  {
    id: "t6",
    name: "Sneha Krishnan",
    role: "Treasurer",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/snehakrishnan",
    email: "sneha.k@vitstudent.ac.in",
    bio: "Managing chapter finances and sponsorship partnerships.",
    team: "treasurer",
    order: 6,
  },
  {
    id: "t7",
    name: "Vikram T",
    role: "Technical Lead",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/vikramt",
    email: "vikram.t@vitstudent.ac.in",
    bio: "Leading technical workshops and CAD training programs.",
    team: "technical",
    order: 7,
  },
  {
    id: "t8",
    name: "Ananya P",
    role: "Design Lead",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/ananyap",
    email: "ananya.p@vitstudent.ac.in",
    bio: "Creating visual identity and design assets for all chapter events.",
    team: "design",
    order: 8,
  },
  {
    id: "t9",
    name: "Rahul V",
    role: "Media Head",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/rahulv",
    email: "rahul.v@vitstudent.ac.in",
    bio: "Managing social media, photography, and video production.",
    team: "media",
    order: 9,
  },
  {
    id: "t10",
    name: "Divya N",
    role: "Events Coordinator",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/divyan",
    email: "divya.n@vitstudent.ac.in",
    bio: "Planning and executing flagship chapter events and competitions.",
    team: "events",
    order: 10,
  },
  {
    id: "t11",
    name: "Mohit S",
    role: "Web Developer",
    department: "Mechanical Engineering",
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop",
    linkedin: "https://linkedin.com/in/mohits",
    email: "mohit.s@vitstudent.ac.in",
    bio: "Building and maintaining the chapter's digital platform.",
    team: "web-development",
    order: 11,
  },
];

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: "an1",
    title: "Aerospace Summit 2026 - Registration Open",
    content: "Registration is now open for our flagship Aerospace Engineering Summit. Limited seats available!",
    type: "event",
    pinned: true,
    createdAt: "2026-03-01",
  },
  {
    id: "an2",
    title: "Boeing Internship Opportunities",
    content: "Boeing India is offering summer internships for ME students. Apply through the member portal.",
    type: "internship",
    pinned: true,
    createdAt: "2026-02-28",
  },
  {
    id: "an3",
    title: "HPVC Team Selection Results",
    content: "Congratulations to the selected team members for ASME HPVC 2026. Check your email for details.",
    type: "competition",
    pinned: false,
    createdAt: "2026-02-25",
  },
];

export const TEAM_GROUPS = {
  "faculty-coordinator": "Faculty Coordinator",
  "faculty-advisor": "Faculty Advisors",
  chairperson: "Chairperson",
  "vice-chairperson": "Vice Chairperson",
  secretary: "Secretary",
  treasurer: "Treasurer",
  technical: "Technical Team",
  design: "Design Team",
  media: "Media Team",
  events: "Events Team",
  editorial: "Editorial Team",
  "public-relations": "Public Relations",
  "web-development": "Web Development Team",
} as const;

export const RESOURCE_CATEGORIES = {
  "mechanical-notes": "Mechanical Notes",
  solidworks: "SolidWorks",
  catia: "CATIA",
  "fusion-360": "Fusion 360",
  ansys: "ANSYS",
  matlab: "MATLAB",
  python: "Python",
  fea: "FEA",
  cfd: "CFD",
  manufacturing: "Manufacturing",
  materials: "Materials",
  "research-papers": "Research Papers",
  "interview-questions": "Interview Questions",
  "resume-templates": "Resume Templates",
} as const;

export const PROJECT_CATEGORIES = {
  design: "Design Projects",
  automobile: "Automobile",
  robotics: "Robotics",
  manufacturing: "Manufacturing",
  thermal: "Thermal Engineering",
  aerospace: "Aerospace",
  automation: "Automation",
  mechatronics: "Mechatronics",
} as const;

export const EVENT_CATEGORIES = {
  "technical-talk": "Technical Talks",
  workshop: "Workshops",
  "industrial-visit": "Industrial Visits",
  "guest-lecture": "Guest Lectures",
  competition: "Competitions",
} as const;

export const GALLERY_CATEGORIES = {
  events: "Events",
  workshops: "Workshops",
  "industrial-visits": "Industrial Visits",
  competitions: "Competitions",
  "team-building": "Team Building",
  achievements: "Achievements",
} as const;

export const ACHIEVEMENT_TYPES = {
  competition: "Competition Winners",
  publication: "Research Publications",
  patent: "Patents",
  internship: "Internships",
  placement: "Placements",
  scholarship: "Scholarships",
  "national-award": "National Awards",
  "international-award": "International Awards",
} as const;
